Hms 1
hmscott4/AlertManagement pull request #69
Opened 2021-05-25 17:46 UTC by hmscott4

Issues: #61, #58, #39

2021-05-26 10:32 UTC, randomnote1 requested changes

2021-05-26 10:32 UTC, randomnote1 commented on AlertManagement/Scripts/Assign-ScomAlert.ps1
> +            $ruleID = $assignmentRule.ID
Indentation doesn't line up

2021-05-26 10:32 UTC, randomnote1 commented on AlertManagement/Scripts/Assign-ScomAlert.ps1
> +        $ruleID = ""
Use single quotes when setting a string value.

2021-05-26 10:32 UTC, randomnote1 commented on AlertManagement/Scripts/Assign-ScomAlert.ps1
> +        $ruleID = ""
Indentation doesn't line up

2021-05-28 12:40 UTC, hmscott4 commented on AlertManagement/Scripts/Assign-ScomAlert.ps1
> +        $ruleID = ""
Fixed

2021-05-28 12:40 UTC, hmscott4 commented on AlertManagement/Scripts/Assign-ScomAlert.ps1
> +            $ruleID = $assignmentRule.ID
Fixed

2021-05-28 12:41 UTC, merged